### ISSUE TITLE
Cannot install from UNC drive share

### ISSUE THREAD

**Issue by pillarsdotnet** [voxpupuli/puppet-sslcertificate#99]
I recently discovered that this module will not install a certificate that is located on a UNC drive share, e.g. `\\NetApp\Sharename\MyCert.pfx`.  The double-slash is ignored, and the path is rewritten as `C:\NetApp\Sharename\MyCert.pfx`, which results in a file-not-found error, but does *not* return failure in creating the resource.  (!!!)

This shortcoming should at least be documented.  Ideally, the module should handle UNC paths correctly, but it should at least return failure if the given path does not exist.

**Comment by pillarsdotnet** [comment]
Hmm... It may be that I needed to use quadruple rather than double backslashes.   Investigating...

**Comment by ghoneycutt** [comment]
Closing due to inactivity and that this may just be a case of the confusing quoting. Please feel free to re-open if needed.

**Comment by ghoneycutt** [comment]
@pillarsdotnet Could you please submit a PR to the README with how you solved this.

**Comment by pillarsdotnet** [comment]
@ghoneycutt  -- Apparently, the quoting rules within a `.yaml` file are different from the quoting rules within a `.pp` file.  Within a puppet manifest, double-backslashes within single-quotes must be quadrupled, as:

```
sslcertificate { 'MyCert.pfx':
  location   => '\\\\NetApp\Sharename\MyCert.pfx`,
  password   => 'Secret',
  root_store => 'LocalMachine',
  store_dir  => 'My',
  thumbprint => 'DC8DDECAF9F2C6E6C4D607D30E951A2BFE675199',
}
```

However, specifying the same values within a `.yaml` file (as for APL) does not have this doubling requirement:

```
profile::iis::ssl_certificate_list:
  MyCert.pfx:
    location: '\\NetApp\Sharename\MyCert.pfx'
    password: 'Secret'
    root_store: 'LocalMachine'
    store_dir: 'My'
    thumbprint: 'DC8DDECAF9F2C6E6C4D607D30E951A2BFE675199'
```
